options:
  logging: CLOUD_LOGGING_ONLY 

steps:
  - name: 'gcr.io/cloud-builders/docker'
    id: 'pull-cache'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        docker pull gcr.io/vicfood-596fd/vicfood:cache || true


  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/vicfood-596fd/vicfood:$COMMIT_SHA', '--cache-from=gcr.io/vicfood-596fd/vicfood:cache', '.']
    id: 'build'


  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: ['run', 'deploy', 'vicfood-gcrun', '--image', 'gcr.io/vicfood-596fd/vicfood:$COMMIT_SHA', '--region', 'us-east4', '--platform', 'managed']
    id: 'deploy'


  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/vicfood-596fd/vicfood:cache', '--cache-from=gcr.io/vicfood-596fd/vicfood:cache', '--target=cache', '.']
    id: 'update-cache'


  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/vicfood-596fd/vicfood:cache']
    id: 'push-cache'


  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud container images delete gcr.io/vicfood-596fd/vicfood:$COMMIT_SHA --force-delete-tags --quiet
    id: 'delete-image'


timeout: '600s'

images:
  - 'gcr.io/vicfood-596fd/vicfood:$COMMIT_SHA'
  - 'gcr.io/vicfood-596fd/vicfood:cache'
