options:
  logging: CLOUD_LOGGING_ONLY 

steps:
  - name: 'gcr.io/kaniko-project/executor:latest'
    id: 'kaniko-build'
    args:
      - --destination=us-east4-docker.pkg.dev/vicfood-596fd/builds/vicfood:$COMMIT_SHA
      - --cache=true
      - --cache-ttl=24h
      - --compressed-caching=false
      - --use-new-run 
      - --cleanup
      - --context=.
      - --dockerfile=./Dockerfile

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: ['run', 'deploy', 'vicfood-gcrun', '--image', 'us-east4-docker.pkg.dev/vicfood-596fd/builds/vicfood:$COMMIT_SHA', '--region', 'us-east4', '--platform', 'managed']
    id: 'deploy'

timeout: '600s'

# options:
#   logging: CLOUD_LOGGING_ONLY 

# steps:
#   - name: 'gcr.io/cloud-builders/docker'
#     id: 'pull-cache'
#     entrypoint: 'bash'
#     args:
#       - '-c'
#       - |
#         docker pull us-east4-docker.pkg.dev/vicfood-596fd/builds/vicfood:cache || true

#   - name: 'gcr.io/cloud-builders/docker'
#     args: ['build', '-t', 'us-east4-docker.pkg.dev/vicfood-596fd/builds/vicfood:$COMMIT_SHA', '--cache-from=us-east4-docker.pkg.dev/vicfood-596fd/builds/vicfood:cache', '--target=deps', '.']
#     id: 'build'

#   - name: 'gcr.io/cloud-builders/docker'
#     args: ['push', 'us-east4-docker.pkg.dev/vicfood-596fd/builds/vicfood:$COMMIT_SHA']
#     id: 'push'

#   - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
#     entrypoint: gcloud
#     args: ['run', 'deploy', 'vicfood-gcrun', '--image', 'us-east4-docker.pkg.dev/vicfood-596fd/builds/vicfood:$COMMIT_SHA', '--region', 'us-east4', '--platform', 'managed']
#     id: 'deploy'

#   - name: 'gcr.io/cloud-builders/docker'
#     args: ['tag', 'us-east4-docker.pkg.dev/vicfood-596fd/builds/vicfood:$COMMIT_SHA', 'us-east4-docker.pkg.dev/vicfood-596fd/builds/vicfood:cache']
#     id: 'tag-cache'

#   - name: 'gcr.io/cloud-builders/docker'
#     args: ['push', 'us-east4-docker.pkg.dev/vicfood-596fd/builds/vicfood:cache']
#     id: 'push-cache'

# timeout: '600s'

# images:
#   - 'us-east4-docker.pkg.dev/vicfood-596fd/builds/vicfood:$COMMIT_SHA'
#   - 'us-east4-docker.pkg.dev/vicfood-596fd/builds/vicfood:cache'
